### ISSUE TITLE
Solomon too high for these values

### ISSUE THREAD

**Issue by alexbonjour** [alexbonjour/rules-of-thumb#23]
Your calculator give results for Solomon that are ~2% higher than the result I get using a spreadsheet.
Siya= 527200, TP = 1.56, AZ = 4000

My calc = 86812

https://docs.google.com/spreadsheets/d/1PYHl6S4WJTLiNp-Z6g7_rvbdn9_i_TCfvrjFq81WQQ4/edit?usp=sharing gives 85100.

I believe they should be identical.

**Comment by ti-to** [comment]
The calculator has two errors, if it is supposed to follow the new math at https://www.reddit.com/r/ClickerHeroes/comments/4naohc/math_and_transcendance/

1. alpha is incorrectly calculated as 1.0 + ftp, when it should be 1.0 + ftp / 100.0 (because of %), leading to wrong atman and kuma values.

2. To offset this, solomon is incorrectly calculated as siya^0.8 * alpha^0.4, when it should be siya^0.8 / alpha^0.4, leading to wrong solomon values.

**Comment by alexbonjour** [comment]
Awesome bug hunting! Thanks!
